### ISSUE TITLE
Release vicuna-13b on replicate

### ISSUE THREAD

**Issue by joehoover** [replicate/cog-vicuna-13b#1]
```[tasklist]
### Tasks
- [ ] https://github.com/replicate/cog-vicuna-13b/issues/2
- [x] tensorize llama weights
- [x] test predictor locally
- [x] push to replicate
- [x] update readme
- [x] get tweets approved
```

**Comment by joehoover** [comment]
I've run into issues converting llama to vicuna. Spent some time debugging, but have not fixed yet.
